const CONFIG={version:'v3.7',api:'https://script.google.com/macros/s/AKfycbwiM61R-bfvWbbkciZBDYorbx9F3hgOXU85f5lyuC78kB1zJe1B4MmmHLw6eVk-XDeS/exec',sheet:'https://docs.google.com/spreadsheets/d/1gJpbr_PZXUoU3smlli7DsJPWUJurqCOZxWb8Ui15YqA/edit',repo:'https://github.com/cinaedvsstudios/actarium',fit:'https://cinaedvsstudios.github.io/chrisfit/',viaticum:'https://cinaedvsstudios.github.io/Viaticum/'};
const S={date:iso(new Date()),desktop:'today',mobile:'all',filter:'all',theme:localStorage.getItem('actarium.theme')||'dark',apps:false,modal:null,selected:new Set(),data:{tasks:[],reminders:[],apps:[],feed:[],events:[],schedule:[]},connection:'Loading…'};
document.documentElement.dataset.theme=S.theme;const app=document.getElementById('app');boot();
async function boot(){render();try{S.data=normalise(await api('bootstrap'));S.connection='Live Sheet connection'}catch(e){console.warn(e);S.data=demo();S.connection='Demo / local view'}render()}
async function api(action,body){if(body){const r=await fetch(CONFIG.api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...body})});if(!r.ok)throw Error(r.status);return r.json()}const u=new URL(CONFIG.api);u.searchParams.set('action',action);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);const j=await r.json();if(j.success===false)throw Error(j.error||'backend');return j}
function normalise(p){return{tasks:(p.tasks||[]).map(task),reminders:(p.reminders||[]).map((x,i)=>({...task(x,i),taskType:'Reminder'})),apps:(p.apps||[]).map(link).filter(x=>/^active$/i.test(x.status||'Active')).sort((a,b)=>a.order-b.order),feed:(p.appFeed||p.app_feed||[]).map(x=>({source:val(x,'sourceApp','source_app','source'),payload:val(x,'payload','payload_json')})),events:(p.viaticumEvents||p.viaticum_events||[]).map(event),schedule:schedule(p)}}
function task(x,i=0){const due=date(val(x,'dueDate','due_date','startDate','start_date','date')||S.date),start=date(val(x,'startDate','start_date','dueDate','due_date','date')||due),end=date(val(x,'endDate','end_date','dueDate','due_date','date')||due),text=`${val(x,'project','area')} ${val(x,'source')} ${val(x,'title')} ${val(x,'notes')}`;return{id:val(x,'id')||`T-${i}`,title:val(x,'title')||'Untitled task',project:val(x,'project','area')||'General',source:val(x,'source')||'Actarium',status:val(x,'status')||'Not started',priority:val(x,'priority')||'Normal',start,end,due,notes:val(x,'notes'),completed:val(x,'completedAt','completed_at'),taskType:val(x,'taskType','task_type')||(/work|nike|zalando|office/i.test(text)?'Work':'Personal')}}
function link(x,i=0){const meta=`${val(x,'label')} ${val(x,'notes')}`.toLowerCase();return{id:val(x,'id')||`A-${i}`,label:val(x,'label')||'Link',emoji:val(x,'emoji')||'🔗',url:val(x,'url'),github:val(x,'githubUrl','github_url'),notes:val(x,'notes'),status:val(x,'status')||'Active',order:+(val(x,'sortOrder','sort_order')||999),group:val(x,'group')||(/n26|paypal|drive|gmail|github|netlify/.test(meta)?'Admin links':/actarium|chrisfit|viaticum|artifex|onda|organon/.test(meta)?'My apps':'Creative links')}}
function event(x){return{date:date(val(x,'date','RealDate')),status:val(x,'status','Status')||'Unsure',statusEmoji:val(x,'statusEmoji','status_emoji')||'🤔',location:val(x,'location','Location'),locationEmoji:val(x,'locationEmoji','location_emoji')||'📍',event:val(x,'event','Event'),eventEmoji:val(x,'eventEmoji','event_emoji')||'🎒',schedule:val(x,'schedule','Schedule')||val(x,'details','Details')}}
function schedule(p){const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];const routine=(p.routine||[]).flatMap(r=>days.map((d,i)=>r[d]?{title:r[d],emoji:r.emoji||(i<5?'💼':'🌙'),days:d.slice(0,3)}:null).filter(Boolean));return routine.concat((p.schedule||[]).map(r=>({title:val(r,'title')||'Scheduled item',emoji:val(r,'emoji')||'🗓️',days:val(r,'days')})))}
function render(){app.innerHTML='';const shell=node('main','shell');shell.append(header(),desktop(),mobile());app.append(shell);if(S.modal)app.append(modal())}
function header(){const h=node('header','top'),card=node('section','day-card');card.innerHTML=`<div class="top-line"><div class="brand"><img src="icon.png" class="logo"><span class="brand-name">ACTARIUM</span><span class="version">${CONFIG.version}</span></div><div class="utility"></div></div><nav class="desktop-tabs"></nav><nav class="mobile-tabs"></nav><div class="day-title"><button class="day-name">${esc(dayName(S.date))}</button><div class="day-date">${esc(dayDate(S.date))}</div></div><div class="day-bottom"><div class="context"></div><div class="actions"></div></div>`;card.querySelector('.utility').append(icon(S.theme==='dark'?'☀️':'🌙',toggleTheme),icon('⚙️',()=>open('settings')));[['today','🌅 Today'],['week','🗓️ Week'],['month','🌘 Month'],['tasks','✅ Tasks']].forEach(([key,label])=>card.querySelector('.desktop-tabs').append(button(label,`tab ${S.desktop===key?'active':''}`,()=>{S.desktop=key;S.apps=false;render()})));[['all','🌐 All'],['tasks','✅ Tasks'],['fit','🥦 ChrisFit'],['viaticum','🎒 Viaticum']].forEach(([key,label])=>card.querySelector('.mobile-tabs').append(button(label,`tab ${S.mobile===key?'active':''}`,()=>{S.mobile=key;S.apps=false;render()})));card.querySelector('.day-name').onclick=()=>open('date');const c=context(),pill=node('span','context-pill');pill.textContent=`${c.emoji} ${c.title}`;card.querySelector('.context').append(pill);card.querySelector('.actions').append(button('🧩 Apps','small-btn',()=>{S.apps=!S.apps;render()}),button('🗄️ Archive','small-btn',()=>open('archive')),button('➕ Add','small-btn accent',()=>open('task')));h.append(card);if(S.apps)h.append(apps());return h}
function apps(){const menu=node('section','apps-menu');['My apps','Admin links','Creative links'].forEach(group=>{const col=node('div','apps-col');col.innerHTML=`<h3>${group}</h3>`;S.data.apps.filter(x=>x.group===group).forEach(x=>{const row=node('div','app-link-row');row.innerHTML=`<a href="${attr(x.url)}" target="_blank" rel="noreferrer"><span>${esc(x.emoji)}</span><span><b>${esc(x.label)}</b>${x.notes?`<small>${esc(x.notes)}</small>`:''}</span></a>${x.github?`<a class="github" href="${attr(x.github)}" target="_blank">🐙</a>`:''}`;col.append(row)});menu.append(col)});return menu}
function desktop(){const wrap=node('section','desktop-view');const range=S.desktop==='week'?weekRange():S.desktop==='month'?monthRange():[S.date,S.date];if(S.desktop==='tasks'){wrap.append(taskCard('🏠 Personal tasks',S.data.tasks.filter(x=>!archived(x)&&!work(x))),taskCard('💼 Work tasks',S.data.tasks.filter(x=>!archived(x)&&work(x))),taskCard('🔔 Reminders',S.data.reminders.filter(x=>!archived(x)),true));return wrap}const grid=node('div','desktop-grid'),left=node('div','stack'),right=node('div','stack');left.append(fitCard(),viaticumCard());const tasks=S.data.tasks.filter(x=>overlap(x,...range)),rems=S.data.reminders.filter(x=>overlap(x,...range));if(S.desktop==='today'){const over=S.data.tasks.filter(x=>!archived(x)&&x.start<S.date);if(over.length)right.append(taskCard('🚨 Outstanding',over,false,'out'))}right.append(taskCard(S.desktop==='today'?'✅ Today tasks':`✅ ${S.desktop} tasks`,tasks,false,'task'),taskCard('🔔 Reminders',rems,true,'rem'));grid.append(left,right);wrap.append(grid);return wrap}
function mobile(){const viewer=node('section','mobile-view card');viewer.append(viewHead());if(S.mobile==='all'||S.mobile==='fit')viewer.append(section('🥦 ChrisFit',fitBody()));if(S.mobile==='all'||S.mobile==='viaticum')viewer.append(section('🎒 Viaticum',viaticumBody()));if(S.mobile==='all'||S.mobile==='tasks')viewer.append(section('✅ Tasks & reminders',tasksBody()));return viewer}
function viewHead(){const names={all:'🌐 All',tasks:'✅ Tasks & reminders',fit:'🥦 ChrisFit',viaticum:'🎒 Viaticum'};const h=node('div','viewer-head');h.innerHTML=`<h2>${names[S.mobile]}</h2>`;return h}
function section(title,body){const s=node('section','viewer-section');s.innerHTML=`<h3>${title}</h3>`;s.append(body);return s}
function fitCard(){const c=node('article','card fit');c.append(cardHead('🥦 ChrisFit',CONFIG.fit),fitBody());return c}
function fitBody(){const data=fitness(),body=node('div','app-body'),grid=node('div','mini-grid');grid.append(mini('Daily Summary',[['🥦 Food',data.df],['🔥 Burn',data.db],['📉 Deficit',data.dd]]),mini('Weekly Summary',[['🥦 Food',data.wf],['🔥 Burn',data.wb],['📉 Deficit',data.wd]]));const weight=node('div','weight');weight.innerHTML=`<b>⚖️ Weight</b><strong>${esc(data.weight)}</strong>${data.bmi?`<span>${esc(data.bmi)}</span>`:''}`;body.append(grid,weight);return body}
function viaticumCard(){const c=node('article','card viaticum');c.append(cardHead('🎒 Viaticum',CONFIG.viaticum),viaticumBody());return c}
function viaticumBody(){const e=S.data.events.find(x=>x.date===S.date)||{},week=S.data.events.filter(x=>inRange(x.date,...weekRange())),next=week.find(x=>x.date>=S.date)||{},body=node('div','app-body'),grid=node('div','mini-grid');grid.append(mini('Daily Summary',[[e.statusEmoji||'🤔',e.status||'Unsure'],[e.locationEmoji||'📍',e.location||'—'],[e.eventEmoji||'🎒',e.event||'Check Viaticum']]),mini('Weekly Summary',[['🗓️ Items',String(week.length)],['📍',locations(week)||'—'],['➡️',next.event||next.location||'—']]));body.append(grid,info('Schedule',e.schedule||'Open Viaticum and check schedule, maps, paid/unpaid, and codes.'));return body}
function cardHead(title,url){const h=node('div','card-head');h.innerHTML=`<h2>${title}</h2><a href="${url}" target="_blank" class="open-link">🔗 Open</a>`;return h}
function mini(title,rows){const b=node('div','mini');b.innerHTML=`<h3>${title}</h3>`;rows.forEach(([a,bv])=>{const r=node('div','summary');r.innerHTML=`<span>${esc(a)}</span><strong>${esc(bv)}</strong>`;b.append(r)});return b}
function info(title,text){const b=node('div','info');b.innerHTML=`<b>${esc(title)}</b><p>${esc(text)}</p>`;return b}
function tasksBody(){const b=node('div','tasks-body'),today=S.data.tasks.filter(x=>overlap(x,S.date,S.date)),rems=S.data.reminders.filter(x=>overlap(x,S.date,S.date));const controls=node('div','task-controls');[['all','🌐 All'],['personal','🏠 Personal'],['work','💼 Work']].forEach(([key,label])=>controls.append(button(label,`filter ${S.filter===key?'active':''}`,()=>{S.filter=key;render()})));controls.append(button('✅ Done selected','small-control',doneSelected),button('➕ New task','small-control',()=>open('task')));b.append(controls,listSection('✅ Tasks',filtered(today)),listSection('🔔 Reminders',rems));return b}
function taskCard(title,items,reminder=false,tone=''){const c=node('article',`card task-card ${tone}`),h=node('div','card-head');h.innerHTML=`<h2>${title}</h2>`;if(!reminder)h.append(button('➕ New task','small-control',()=>open('task')));c.append(h,taskList(items));return c}
function listSection(title,items){const s=node('section','list-section');s.innerHTML=`<h4>${title}</h4>`;s.append(taskList(items));return s}
function taskList(items){const list=node('div','list');items.forEach(x=>list.append(taskRow(x)));if(!items.length){const p=node('p','empty');p.textContent='No items here.';list.append(p)}return list}
function taskRow(x){const r=node('article',`task-row ${done(x)?'done':''}`),check=node('button',`check ${S.selected.has(String(x.id))?'selected':''}`);check.type='button';check.textContent=done(x)?'✓':'';check.onclick=()=>{const id=String(x.id);S.selected.has(id)?S.selected.delete(id):S.selected.add(id);render()};const detail=node('button','task-detail');detail.type='button';detail.innerHTML=`<h3>${done(x)?'✅ ':''}${work(x)?'💼':'🏠'} ${esc(x.title)}</h3><p>${esc(x.project)} · ${esc(x.start||x.due)}</p><div class="meta"><span>${esc(done(x)?'✅ Done':x.status)}</span><span>${esc(x.priority)}</span></div>`;detail.onclick=()=>open('task',x);const more=icon('🔎',()=>open('task',x));more.className='more';r.append(check,detail,more);return r}
function filtered(items){return S.filter==='work'?items.filter(work):S.filter==='personal'?items.filter(x=>!work(x)):items}
function modal(){const back=node('div','modal-back'),box=node('section','modal');back.append(box);back.onclick=e=>{if(e.target===back)close()};if(S.modal.type==='settings')settings(box);else if(S.modal.type==='archive')archive(box);else if(S.modal.type==='date')dateModal(box);else taskModal(box,S.modal.item||{});return back}
function modalHead(title){const h=node('div','modal-head');h.innerHTML=`<h2>${title}</h2>`;h.append(icon('✕',close));return h}
function settings(box){box.append(modalHead('⚙️ Settings'));const b=node('div','modal-body');[['📊 Open Actarium Sheet',CONFIG.sheet],['🐙 Open GitHub repo',CONFIG.repo],['🥦 Open ChrisFit',CONFIG.fit],['🎒 Open Viaticum',CONFIG.viaticum]].forEach(([a,u])=>{const l=document.createElement('a');l.className='settings-link';l.href=u;l.target='_blank';l.textContent=a;b.append(l)});b.append(info(CONFIG.version,S.connection));box.append(b)}
function archive(box){box.append(modalHead('🗄️ Archive'));const b=node('div','modal-body');b.append(taskList(S.data.tasks.filter(archived)));box.append(b)}
function dateModal(box){box.append(modalHead('📅 Pick date'));const b=node('div','modal-body'),i=document.createElement('input');i.type='date';i.className='input';i.value=S.date;b.append(i,button('💾 Save','save',()=>{S.date=i.value||S.date;close()}));box.append(b)}
function taskModal(box,x){box.append(modalHead(x.id?'✏️ Edit task':'➕ New task'));const b=node('div','modal-body'),title=input('Title',x.title||''),project=input('Project',x.project||'General'),dateInput=input('Date',x.start||S.date,'date');b.append(title.wrap,project.wrap,dateInput.wrap,button('💾 Save','save',async()=>{const item={...x,id:x.id||`T-${Date.now()}`,title:title.input.value||'Untitled task',project:project.input.value||'General',start:dateInput.input.value||S.date,end:dateInput.input.value||S.date,due:dateInput.input.value||S.date,status:x.status||'Not started',priority:x.priority||'Normal',taskType:x.taskType||'Personal',source:x.source||'Actarium'};const n=S.data.tasks.findIndex(t=>String(t.id)===String(item.id));n>=0?S.data.tasks.splice(n,1,item):S.data.tasks.unshift(item);close();try{await api('saveTask',{task:item})}catch(e){console.warn(e)}}));box.append(b)}
function input(label,value,type='text'){const w=node('label','field');w.innerHTML=`<span>${label}</span>`;const i=document.createElement('input');i.type=type;i.value=value;i.className='input';w.append(i);return{wrap:w,input:i}}
async function doneSelected(){const ids=[...S.selected];if(!ids.length){alert('Tick one or more tasks first.');return}const completedAt=new Date().toISOString();S.data.tasks=S.data.tasks.map(x=>ids.includes(String(x.id))?{...x,status:'Done',completed:completedAt}:x);S.selected.clear();render();try{await api('markTasksDone',{ids,completedAt})}catch(e){console.warn(e)}}
function open(type,item){S.apps=false;S.modal={type,item};render()}function close(){S.modal=null;render()}function toggleTheme(){S.theme=S.theme==='dark'?'light':'dark';localStorage.setItem('actarium.theme',S.theme);document.documentElement.dataset.theme=S.theme;render()}
function context(){const e=S.data.events.find(x=>x.date===S.date);if(e?.location&&!/^(berlin|home)$/i.test(e.location))return{emoji:'🎒',title:`Trip in progress · ${e.location}`};const d=asDate(S.date).toLocaleDateString('en-GB',{weekday:'short'}).toLowerCase();return S.data.schedule.find(x=>!x.days||x.days.toLowerCase().includes(d))||{emoji:'💼',title:'Work day'}}
function fitness(){const f=S.data.feed.find(x=>/chrisfit/i.test(x.source));let d={};try{d=JSON.parse(f?.payload||'{}')}catch{}return{df:d.dailyFood||'0 / 1500',db:d.dailyBurn||'0 / 2500',dd:d.dailyDeficit||'0 / -500',wf:d.weeklyFood||'— / 10500',wb:d.weeklyBurn||'— / 17500',wd:d.weeklyDeficit||'— / -3500',weight:d.weight||'— kg',bmi:d.bmi||''}}
function done(x){return /^done$/i.test(x.status||'')||!!x.completed}function archived(x){return done(x)||/cancelled|deleted/i.test(x.status||'')}function work(x){return /work/i.test(x.taskType||'')||/work|zalando|nike|office/i.test(`${x.project} ${x.source} ${x.title} ${x.notes}`)}function overlap(x,start,end){return(x.start||x.due)<=end&&start<=(x.end||x.due||x.start)}function inRange(v,a,b){return v&&v>=a&&v<=b}function weekRange(){const d=asDate(S.date),m=new Date(d);m.setDate(d.getDate()-((d.getDay()+6)%7));const e=new Date(m);e.setDate(m.getDate()+6);return[iso(m),iso(e)]}function monthRange(){const d=asDate(S.date);return[iso(new Date(d.getFullYear(),d.getMonth(),1)),iso(new Date(d.getFullYear(),d.getMonth()+1,0))]}function locations(xs){return[...new Set(xs.map(x=>x.location).filter(Boolean))].slice(0,2).join(', ')}function dayName(v){return asDate(v).toLocaleDateString('en-GB',{weekday:'long'})}function dayDate(v){return asDate(v).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}function date(v){return v?iso(v):''}function iso(v){const d=asDate(v);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function asDate(v){if(v instanceof Date)return v;const s=String(v||'');if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c)}const d=new Date(s);return isNaN(d)?new Date():d}function val(x,...keys){for(const k of keys)if(x?.[k]!==undefined&&x?.[k]!==null&&String(x[k]).trim()!=='')return x[k];return''}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(v){return esc(v).replace(/`/g,'')}function node(tag,cls=''){const e=document.createElement(tag);if(cls)e.className=cls;return e}function button(label,cls,fn){const b=node('button',cls);b.type='button';const m=String(label).match(/^(\S+)\s*(.*)$/);b.innerHTML=`<span class="emoji">${esc(m?.[1]||'')}</span>${m?.[2]?`<span>${esc(m[2])}</span>`:''}`;b.onclick=fn;return b}function icon(label,fn){const b=node('button','icon');b.type='button';b.textContent=label;b.onclick=fn;return b}
function demo(){return normalise({tasks:[{id:'T1',title:'Connect Actarium to the Sheet backend',project:'Apps',priority:'High',date:S.date},{id:'T2',title:'Review Nike PO confirmations',project:'Zalando',task_type:'Work',priority:'High',date:S.date}],reminders:[{id:'R1',title:'Check Actarium after deployment',project:'Apps',date:S.date}],apps:[{label:'Actarium',emoji:'📋',url:'https://cinaedvsstudios.github.io/actarium/',group:'My apps',status:'Active'},{label:'ChrisFit',emoji:'⚖️',url:CONFIG.fit,group:'My apps',status:'Active'},{label:'Viaticum',emoji:'🎒',url:CONFIG.viaticum,group:'My apps',status:'Active'}],routine:[{emoji:'💼',monday:'Work day',tuesday:'Work day',wednesday:'Work day',thursday:'Work day',friday:'Work day'}],viaticumEvents:[{date:S.date,status:'Unsure',location:'Berlin',event:'Check Viaticum',schedule:'Open Viaticum and check schedule, maps, paid/unpaid, and codes.'}]})}